# Generated by Django 4.2.30 on 2026-06-02 04:31

from django.db import migrations


def set_existing_verified(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(is_active=True).update(is_email_verified=True)


def reverse_set_existing_verified(apps, schema_editor):
    pass  # No reverse needed


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RunPython(set_existing_verified, reverse_set_existing_verified),
    ]
