# Generated by Django 6.0.5 on 2026-05-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_initial'),
        ('shop', '0002_alter_medicine_is_active_alter_medicine_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(blank=True, help_text='Medicines approved under this prescription', related_name='prescriptions', to='shop.medicine'),
        ),
    ]
