# Generated by Django 4.2.30 on 2026-06-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_medicine_is_active_alter_medicine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.URLField(blank=True, help_text='Supabase image URL', max_length=500, null=True),
        ),
    ]
