# Generated by Django 4.2.30 on 2026-06-03 04:23

from django.db import migrations, models
import shop.supabase_storage


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_remove_medicine_image_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=shop.supabase_storage.SupabaseStorage(bucket_name='medicines'), upload_to='medicines/'),
        ),
    ]
